### ISSUE TITLE
Do you have implemented equivalent of `@automerge/automerge-repo` and `@automerge/automerge-repo-network-websocket` in Golang?

### ISSUE THREAD

**Issue by stephane-klein** [astromechza/automerge-experiments#1]
Hello, I'd like to get in touch with you to talk about [automerge-go](https://github.com/automerge/automerge-go).

I want to implement a golang CLI project based on [Automerge](https://automerge.org/) 🙂.

I haven't seen an equivalent of the [`@automerge/automerge-repo`](https://www.npmjs.com/package/@automerge/automerge-repo) project, nor [`@automerge/automerge-repo-network-websocket`](https://github.com/automerge/automerge-repo/tree/main/packages/automerge-repo-network-websocket) in *golang*.

I saw your project <https://github.com/astromechza/automerge-experiments>, and I have a question: does this [`/main/cmd/four`](https://github.com/astromechza/automerge-experiments/tree/main/cmd/four) file contain the implementation equivalent of `@automerge/automerge-repo` and `@automerge/automerge-repo-network-websocket` ?  
If so, would it be possible for me to reuse your code? Is this a good idea?

Best regards,
Stéphane

**Comment by astromechza** [comment]
Hey! Yeah /main/cmd/four was a basic websocket implementation that seems to work. I've written a better implementation up at https://github.com/aurelian-one/au/blob/main/pkg/auws/auws.go. 

Although it's not the same as the official one from automerge-repo which supports more message types and has a more complex protocol I think. It really depends what you need I think :) The automerge-repo JS one provides support for multiple concurrent documents and complex sharing protocols. I haven't really used it yet.
